docs/overview.rst, docs/using/combining.rst, docs/using/configuration.rst, docs/using/grids.rst, docs/using/introduction.rst, docs/using/methods.rst, docs/using/opening.rst, docs/using/other.rst, docs/using/subsetting.rst
Fixing typos from 'Overview' to 'Using Datasets --> Configuration'.
=> Documentation review

CHANGELOG.md, src/anemoi/datasets/create/loaders.py, src/anemoi/datasets/create/statistics/__init__.py
=> Negative variance

src/anemoi/datasets/create/check.py
update frequency checking in dataset names
=> update frequency checking in dataset names

src/anemoi/datasets/commands/inspect.py
fix inspect output for frequency
=> fix inspect output for frequency

CHANGELOG.md, pyproject.toml, src/anemoi/datasets/create/input.py
Fix a test that failed with the changes to support hindcasts
=> Fix failing test

CHANGELOG.md, src/anemoi/datasets/commands/publish.py, src/anemoi/datasets/create/__init__.py
Add anemoi-datasets publish, relying on anemoi-registry.
Save user recipe in the datasets.
=> publish dataset

CHANGELOG.md, docs/conf.py, src/anemoi/datasets/data/masked.py, src/anemoi/datasets/data/stores.py
----
📚 Documentation preview 📚: https://anemoi-datasets--102.org.readthedocs.build/en/102/
=> More verbosity

CHANGELOG.md, src/anemoi/datasets/create/functions/__init__.py, src/anemoi/datasets/create/statistics/__init__.py
due to rounding errors. Setting it to zero when it is negative,
=> fix negative variance  for constant variables

src/anemoi/datasets/create/__init__.py, src/anemoi/datasets/create/functions/sources/xarray/metadata.py, src/anemoi/datasets/create/functions/sources/xarray/time.py, src/anemoi/datasets/create/functions/sources/xarray/variable.py
A fix for https://github.com/ecmwf/anemoi-datasets/issues/116 and https://github.com/ecmwf/anemoi-datasets/issues/155
=> Fix for #155 and #116

docs/overview.rst
Add an animation of dataset creation.
-   [x] Documentation update
-   [ ] My code follows the style guidelines of this …
=> docs: add animation

src/anemoi/datasets/create/statistics/__init__.py
faster and use less memory,
-   [ …
=> feat: Use set in computing statistics, faster and use less memory

docs/building/filters.rst, docs/building/filters/regrid.rst, docs/building/filters/yaml/regrid1.yaml, docs/building/filters/yaml/regrid2.yaml, docs/building/sources.rst, docs/building/sources/eccc_fstd.rst, docs/building/sources/mars.rst, docs/building/sources/yaml/eccc_fstd.yaml, docs/building/sources/yaml/mars-cds.yaml
Recent change were made in the anemoi-datasets sources to support ECCC standard format files and allow external user to download ERA5 data using the CDS API. Additionally, a filter was added to interpolate the retrieved data on an arbitrary grid. These changes haven't been documented yet. This PR doesn't modify the code, it only provides a description for these change in the documentation.
-   [x] Documentation update
-   [x] I have performed a self-review of my code
-   [ ] I ran …
=> docs: update doc with eccc-fstd, cdsapi and regrid

.readthedocs.yaml
- **feat: fix readthedocs**
-   [ …
=> docs: fix readthedocs

src/anemoi/datasets/data/dataset.py, src/anemoi/datasets/data/stores.py
=> fix: fix to_index

src/anemoi/datasets/dates/__init__.py
=> feat: better logging for group of dates

src/anemoi/datasets/data/ensemble.py
=> fix: fix for bug #237

src/anemoi/datasets/create/filters/transform.py
=> fix: modify execute function signature

src/anemoi/datasets/data/dataset.py
=> feat: better error message

src/anemoi/datasets/create/filters/transform.py
=> fix: fix typo

src/anemoi/datasets/create/__init__.py, src/anemoi/datasets/create/config.py
-   [x] I have performed a self-review of my code …
=> feat: add environment variables in recipe

src/anemoi/datasets/create/sources/accumulations.py, src/anemoi/datasets/create/sources/accumulations2.py, tests/create/accumulation.yaml, tests/create/test_create.py
=> feat: 24h accumulations for era5

src/anemoi/datasets/create/filters/pressure_level_relative_humidity_to_specific_humidity.py, src/anemoi/datasets/create/filters/pressure_level_specific_humidity_to_relative_humidity.py, src/anemoi/datasets/create/filters/wz_to_w.py
=> fix: Remove hardcoded indices and get pressure levels from keys directly

src/anemoi/datasets/commands/grib-index.py
=> fix: grib-index command default

pyproject.toml
=> fix: update version of transform

pyproject.toml
=> fix: pin version of numcodecs

src/anemoi/datasets/data/stores.py
If a URL to a zip file is provided in `open_dataset`, the file is automatically downloaded in $TMPDIR.
-   [ ] I have tested that new dependencies themselves are …
=> feat: downloading zip files if needed

src/anemoi/datasets/commands/copy.py
=> fix: fix copy

src/anemoi/datasets/commands/create.py
Fix copy pasta bug in parallel additions
=> fix: Proper indent for parallel additions

src/anemoi/datasets/commands/scan.py, src/anemoi/datasets/create/input/result.py, src/anemoi/datasets/create/sources/accumulations.py, src/anemoi/datasets/data/forwards.py
Implement a version of `accumulation` for data that have an accumulation that resets to 0 regularly (e.g. every 24h)
-   [ ] I have tested that new dependencies themselves …
=> feat: reset accumulations

pyproject.toml, tests/create/test_sources.py
I've updated the dependencies to include s3fs so that the xarray tests are no longer skipped after a clean dev install. I've also removed the h5py requirement to run the test (as it's not needed - test passes without this).
The s3fs minimum version is set to avoid a slow performance warning from fsspec (see dask/dask#10276, dask/dask#10397 which explains why this is required, and the [fsspec line where warning is raised](https://github.com/fsspec/filesystem_spec/blob/aa1a301f13d086c9c664c61f3838911418f52905/fsspec/registry.py#L285)). …
=> chore(deps,test): Update dependencies to include s3fs for xarray test

src/anemoi/datasets/check.py, src/anemoi/datasets/commands/check.py, src/anemoi/datasets/commands/copy.py, src/anemoi/datasets/create/__init__.py
Add an extra check when copying zarr.
-   [ ] My code follows the style guidelines of this …
=> feat: work on check

src/anemoi/datasets/create/sources/accumulations.py
Reorder lines that triggered assertion that cause bug #354
Fix bug #354
=> fix: regression in accumulations #354

pyproject.toml
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)
=> chore: update anemoi-utils dependency version

src/anemoi/datasets/create/zarr.py, tests/create/utils/compare.py
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)
=> fix: cleaning _build when building datasets

src/anemoi/datasets/create/sources/accumulations.py, src/anemoi/datasets/create/sources/accumulations2.py, src/anemoi/datasets/create/sources/anemoi_dataset.py, src/anemoi/datasets/create/sources/constants.py, src/anemoi/datasets/create/sources/empty.py, src/anemoi/datasets/create/sources/forcings.py, src/anemoi/datasets/create/sources/grib.py, src/anemoi/datasets/create/sources/grib_index.py, src/anemoi/datasets/create/sources/hindcasts.py, src/anemoi/datasets/create/sources/legacy.py, src/anemoi/datasets/create/sources/mars.py, src/anemoi/datasets/create/sources/netcdf.py, src/anemoi/datasets/create/sources/opendap.py, src/anemoi/datasets/create/sources/recentre.py, src/anemoi/datasets/create/sources/source.py, src/anemoi/datasets/create/sources/tendencies.py, src/anemoi/datasets/create/sources/xarray_support/__init__.py, src/anemoi/datasets/create/sources/xarray_zarr.py, src/anemoi/datasets/create/sources/zenodo.py
Reduces the complexity of legacy sources by moving to straightforward class inheritance and implementation, removing the need for the decorator and dynamically generated classes. 
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement. …
=> refactor: reduce complexity of legacy sources
