docs/using/subsetting.rst
According to https://github.com/ecmwf/anemoi-datasets/blame/3d2ed9079c3e1cfda7a45cf3d0b00a2f9c05d9cc/src/anemoi/datasets/data/misc.py#L137 the time must always be specified as `hh:mm:ss`.
As an alternative to fixing the docs, I would see quite a few advantages in following the ISO 8601 standard and in using the python package `isodate` to parse dates.
=> Fix time format in docs

src/anemoi/datasets/data/stores.py
The code crashed with `DEBUG_ZARR_LOADING=1` and it took me a while to figure out what was going on until I realized, that the debugging assumes `DirectoryStore` while other formats are supported by `zarr.convenience.open` in principle.
=> Help the user debugging stores.py

src/anemoi/datasets/dates/groups.py
Missing dates read from a yaml config are datetime objects, the function `no_time_zone` fails when it is called with a datetime object. The change aims at transforming missing dates to isoformat before applying `no_time_zone` as it is the case with other dates.
=> Normalize missing dates before removing time zone

.gitattributes, CHANGELOG.md
Suggested merge strategy to avoid changelog merge conflicts: https://github.com/olivierlacan/keep-a-changelog/discussions/587
Should help us with most trivial changes, we'll have to see if it works trivially on the Release updates.
=> Change the merge strategy for Changelog to Union

CHANGELOG.md, src/anemoi/datasets/create/__init__.py, src/anemoi/datasets/create/functions/sources/xarray/field.py, src/anemoi/datasets/create/functions/sources/xarray/metadata.py, src/anemoi/datasets/create/input.py, src/anemoi/datasets/dates/__init__.py, tests/xarray/test_netcdf.py, tests/xarray/test_opendap.py, tests/xarray/test_zarr.py
Addressing https://github.com/ecmwf/anemoi-datasets/issues/46
=> Bug fix when creating dataset from zarr

src/anemoi/datasets/create/input.py
It seems that with commit 53ab37d4422e4e658c9d5196438d338b74ae7fe2, one renaming of `dates` to `group_of_dates` in the `StepFunctionResult` class was missed: 
https://github.com/ecmwf/anemoi-datasets/blob/647e2165df62e25036714476344feefb0aba6477/src/anemoi/datasets/create/input.py#L780-L801
This PR fixes that.
=> bugfix: rename dates to group_of_dates

src/anemoi/datasets/create/functions/sources/accumulations.py
This PR adds the appropriate `data_accumultation_period` and `base_times`  kwargs when calculating accumulations from mars CERRA `('rr', 'oper')` data.
=> feature: add accumulation KWARGS for CERRA

.github/workflows/python-publish.yml, .github/workflows/python-pull-request.yml, CHANGELOG.md
This PR pins the python versions for the checks in the PR and publish workflows to 3.9 ... 3.12.
=> ci: pin python versions

docs/using/missing.rst
Anemoi-training has internal handling that deals with missing dates in the dataset https://github.com/ecmwf/anemoi-training/blob/develop/src/anemoi/training/utils/usable_indices.py, and when training on a dataset with missing dates you do not have to specify this in the dataloader config. 
The current documentation on missing dates is confusing because it states that you should specify skip_missing_dates and expected_access which does not work with how missing dates are handled in anemoi-training. I realise that anemoi-datasets can be used for applications outside anemoi-training where the skip_missing_dates functionality can be useful, so I propose adding a short section on how to deal with missing_dates in anemoi-training since this will be the most common use case. 
----
📚 …
=> Update to documentation on using missing dates

.github/workflows/ci.yml, .github/workflows/python-pull-request.yml
Simplify ci: run on develop, and on sundays. And disable downstream-ci-hpc. And test only python 3.11. And test only once when PR are updated. And shortest name to read the full description on github.ci. And test with only ubuntu.
=> Simplify ci: run on develop

CHANGELOG.md, src/anemoi/datasets/data/dataset.py
This PR fixes a bug where int64 objects in the metadata raised `TypeError: Object of type int64 is not JSON serializable` by converting them to a python-native int.
=> fix: Ensure metadata serialization handles numpy.integer properly

CHANGELOG.md, src/anemoi/datasets/data/grids.py
This PR fixes a bug with slicing Cutout datasets where slicing the grid dimension didn't work: 
```
cfg = {
"cutout": [
{
"dataset": "metno-meps-archive-det-opendap-2p5km-2020-2023-6h-v1", 
"thinning": 25
},
{
"dataset": "aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6"
}
], "adjust": "all"
}
ds = open_dataset(cfg)
sample = ds[1324:1327, :, :, :]
print(sample.shape)
sample = ds[1324:1327, :, :, 0:20000]
print(sample.shape)
```
previously gave
```
(3, 85, 1, 41459)
(3, 85, 1, 41459)
```
now gives
```
(3, 85, 1, 41459)
(3, 85, 1, 20000)
```
@b8raoult @floriankrb @JPXKQX @paulina-t
=> Fix cutout slicing of grid dimension

src/anemoi/datasets/data/dataset.py
When calculating sample indices, make sure that at least one sample is included.
Example of the problem:
```
$ anemoi-datasets create example.yaml test.zarr
[..]
File "/home/users/partio/src/anemoi-datasets/src/anemoi/datasets/data/dataset.py", line 471, in _compute_constant_fields_from_a_few_samples
p = slice(0, count, count // (sample_count - 1))
~~~~~~^^~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
```
example.yaml:
```
dates:
start: 2024-10-12T14:00:00Z
end: 2024-10-12T14:00:00Z
frequency: 1h
input:
join:
- grib:
path: example.grib2
param: [2t]
levtype: sfc
```
=> Fix division-by-zero when computing statistics for a single-time dataset

docs/index.rst, docs/naming_conventions.rst, src/anemoi/datasets/create/check.py
----
📚 Documentation preview 📚: https://anemoi-datasets--153.org.readthedocs.build/en/153/
=> accept frequency in minute in dataset names

docs/index.rst, docs/using/code/number1_.py, docs/using/code/number2_.py, docs/using/ensembles.rst, docs/using/selecting.rst, src/anemoi/datasets/data/dataset.py, src/anemoi/datasets/data/ensemble.py, src/anemoi/datasets/data/merge.py
This feature allows the selection of one or more members of an ensemble dataset:
```Python
open_dataset("path-to-zarr", number=1)
```
and 
```Python
open_dataset("path-to-zarr", number=[1, 3, 5])
```
----
📚 Documentation preview 📚: https://anemoi-datasets--156.org.readthedocs.build/en/156/
=> Allow selection of one or more members in an ensemble dataset

src/anemoi/datasets/data/dataset.py
**Quick summary:**
Added another reordering option reorder="sort" which sorts the variables alphabetically to enable transfer learning for stretched grid.
**Why, and what is the purpose?**
During transfer learning of stretched-grid model, the cutout and the option adjust='all' functionality is used. This will result that the combined dataset (ds1 and ds2) will have their variable list sorted alphabetically. However, then the pretrained model 
needs to follow this type of sorting. This implementation will reorder the variable list to sort them alphabetically, hence enabling transfer learning when use multiple datasets when using reorder='sort'.
I have done some test, and also created some units tests, but unsure on where to put LAM dataset in order to make the testing work. For now I will …
=> Added reorder sort string, which sorts variables alphabetically.

docs/building/introduction.rst
I’m currently learning the Anemoi framework and building my own dataset as part of the process. While reviewing the documentation, I noticed a few grammar mistakes and decided to contribute by correcting them. This is my first contribution to the project, and I’ve made updates to docs/building/introduction.rst based on my understanding.
Notes
I’ve forked the repository, created a branch with the changes, and am now raising this PR to address the issue. As I’m new to contributing, I apologize in advance for any mistakes. I’m eager to learn and welcome any feedback or guidance you can provide.
Thank you!
----
📚 Documentation preview 📚: https://anemoi-datasets--165.org.readthedocs.build/en/165/
=> docs: correct documentation mistakes and typos

src/anemoi/datasets/data/dataset.py
An error in a conditional causes the Number class to be used when it shouldn't, in some cases.
=> fix: Fix bug in handling Number in Dataset._subset

src/anemoi/datasets/create/functions/filters/rename.py, src/anemoi/datasets/create/functions/filters/single_level_specific_humidity_to_relative_humidity.py, src/anemoi/datasets/create/functions/sources/xarray/coordinates.py, src/anemoi/datasets/create/functions/sources/xarray/fieldlist.py, src/anemoi/datasets/create/functions/sources/xarray/variable.py, src/anemoi/datasets/create/statistics/__init__.py, src/anemoi/datasets/data/complement.py, src/anemoi/datasets/data/dataset.py, src/anemoi/datasets/data/grids.py
Some docstrings were broken after the introduction of `docsig` in the pre-commit. Docstrings still need some TLC in the future, but now they at least pass qa again.
=> chore(qa): Fix docstrings

src/anemoi/datasets/create/input/template.py
When creating forcings using a data source template, there is code that looks for a string that's something like ${input.join.0.datasource}. For example, datasource could be "mars", "netcdf", or "xarray-zarr". However, this code fails 
for data sources like "xarray-zarr" because the string has a "-" in it. I tracked this down to this regular expression: https://github.com/ecmwf/anemoi-datasets/blob/998cc8f2d922f792ac38f0f825228f9dedc15c26/src/anemoi/datasets/create/input/template.py#L70
By explicitly allowing "-" characters (this PR), xarray-zarr data sources can now be used as a template for creating forcings.
-   [ ] Breaking change (fix or feature that would …
=> fix: create forcings based on xarray-zarr template

src/anemoi/datasets/create/functions/sources/xarray/flavour.py
Small change to accept rotated pole grid x and y coordinates. The grid_latitude and grid_longitude standard names are recognized by the cf-conventions.
=> feat: add coordinate standard_name for rotated pole grid

src/anemoi/datasets/create/functions/sources/xarray/coordinates.py, src/anemoi/datasets/create/functions/sources/xarray/metadata.py
Changes in this PR allow cases where netCDF files / xarray.datasets have dimensions with only a single value.
e.g. only 1 single date / valid_datetime
No issue made (yet)
-   [x] I have performed a self-review of my code …
=> fix: allow xarrays with single value dimensions

src/anemoi/datasets/create/filters/transform.py, src/anemoi/datasets/data/__init__.py, src/anemoi/datasets/data/misc.py
Add method to save anemoi dataset  from the recipe used to open it. Write incrementally in a zarr store, adds metadata, recipe used for tracking. Possibility of parallelising without compromising the data order. 
Some people (including myself) complained on slack the method did not exist.
-   [x] I have performed a self-review of my code
-   [ ] I ran the [complete Pytest test](https://anemoi.readthedocs.io/projects/training/en/latest/dev/testing.html) …
=> feat: save opened anemoi_dataset

.readthedocs.yaml, docs/Makefile, docs/_templates/apidoc/package.rst.jinja, docs/modules/create.rst, docs/modules/data.rst, docs/modules/filters.rst, docs/modules/sources.rst, docs/scripts/api_build.sh, pyproject.toml
=> docs: Add API Docs

docs/using/code/trimedge1_.py, docs/using/grids.rst, src/anemoi/datasets/data/dataset.py, src/anemoi/datasets/data/masked.py, tests/test_data.py, tests/test_data_gridded.py
This PR introduces time_edge as an argument to open_dataset. This allows the user to trim away a set number of gridpoints along the edge of LAM datasets.
**NOTE**: I don't fully understand what the following functions do: mutate(), tree(), forwards_subclass_metadata_specific()
I have imitated what the other Masked classes provide, but would appreciate if a reviewer could look through.
-   [X] New feature (non-breaking change which adds functionality)
LAM datasets often have relaxation zones along the boundary, which needs to be removed when training model since the data can be faulty (e.g. in the …
=> feat: add trim_edge dataset filter

src/anemoi/datasets/commands/copy.py
Ensure that `anemoi-datasets copy` works with http/https
-   [ ] My code follows the style …
=> feat: copy datasets from http(s) sources

pyproject.toml
Setting a minimum version of s3fs in #297 introduced an incompatibility when installing `anemoi-datasets[all]` together with `anemoi-utils[all]`, causing the dependency resolver to look at every single version of boto3. 
There were good reasons for having a minimum s3fs, but we need to find the cause of this conflict with utils first before setting it again.
```
$ pip install anemoi-datasets[all] anemoi-utils[all]
...
Collecting boto3 (from anemoi-datasets[all])
Using cached boto3-1.35.99-py3-none-any.whl.metadata (6.7 kB)
INFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.
Using cached boto3-1.35.98-py3-none-any.whl.metadata (6.7 kB)
Using cached boto3-1.35.97-py3-none-any.whl.metadata (6.7 kB) …
```
=> chore(deps): Relax s3fs spec

pyproject.toml
earthkit-data 0.14 comes with some breaking changes that break creation of datasets, see #320
While we examine the impact of these changes on datasets and the other anemois, temporarily set `earthkit-data<0.14` to get back to a working state.
=> chore(deps): earthkit-data<0.14

pyproject.toml, src/anemoi/datasets/create/sources/grib.py, src/anemoi/datasets/create/sources/patterns.py
=> fix: adapt to earthkit 0.14 (ignore_keys issue)

src/anemoi/datasets/create/sources/xarray_support/variable.py, tests/xarray/test_variable.py
This modifies the code for `anemoi.datasets.create.sources.xarray_support.variable.Variable.sel()`to handle the situation where a `Variable` is scalar. This also includes some basic unit testing.
When trying to create datasets from netcdf files, I would hit an issue when one of my coordinates was a scalar as [this line would fail](https://github.com/ecmwf/anemoi-datasets/blob/2baa24ec5e596221fd06bcc24c0f37c85f3fdeff/src/anemoi/datasets/create/sources/xarray_support/variable.py#L224).
I am working with lots of netcdf files where each netcdf file represents a single time step so the time coordinate is scalar
n/a
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a …
=> feat: Extend xarray Variable.sel to handle scalar variables

pyproject.toml
During the tests, ` "--numprocesses=auto",` gives a nice parallel run but when the number of processors is very large (on an HPC), the number of process is too large and the tests are actually slower.
Using the appropriate option solves the issue (see details here https://github.com/pytest-dev/pytest-xdist/issues/337 has a fix for this)
By opening this …
=> chore: Speed up the tests with less parallelisation

src/anemoi/datasets/create/config.py
Fix as a pre-requisite to https://github.com/ecmwf/anemoi-utils/pull/223 because
the class hiearchy will change and the removed line created an exception.
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)
=> fix: remove config_path in Config

src/anemoi/datasets/commands/inspect.py
Bug fix for #422 (Inspect command shows dataset not initialised after successful completion)
Closes #422 
By opening this pull request, I affirm that all authors agree to the [Contributor License Agreement.](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md)
=> fix: anemoi inspect wrong message
